CREATE TABLE `lostandfound`.`Claimed_item` (`CLAIM_ID` INT(11) NOT NULL AUTO_INCREMENT , `F_ID` INT(11) NOT NULL , `CLAMINGUSER_ID` VARCHAR(20) NOT NULL , `DATE_TIME` DATETIME NOT NULL , `OBJECT_NAME` VARCHAR(100) NOT NULL , `Description` VARCHAR(200) NOT NULL , PRIMARY KEY (`CLAIM_ID`)) ENGINE = InnoDB;

CREATE TABLE `lostandfound`.`Found_Item` (`F_ID` INT(11) NOT NULL AUTO_INCREMENT , `USER_ID` VARCHAR(20) NOT NULL , `F_NAME` VARCHAR(100) NOT NULL , `DESCRIPTION` VARCHAR(250) NOT NULL , `LOCATION` VARCHAR(100) NOT NULL , `DATE_TIME` DATETIME NOT NULL , PRIMARY KEY (`F_ID`)) ENGINE = InnoDB;

CREATE TABLE `lostandfound`.`Lost_Item` (`L_ID` INT(11) NOT NULL AUTO_INCREMENT , `USER_ID` VARCHAR(20) NOT NULL , `L_NAME` VARCHAR(100) NOT NULL , `DESCRIPTION` VARCHAR(250) NOT NULL , `LOCATION` VARCHAR(250) NOT NULL , `DATE_TIME` DATETIME NOT NULL , PRIMARY KEY (`L_ID`)) ENGINE = InnoDB;

CREATE TABLE `lostandfound`.`user` (`USER_ID` VARCHAR(20) NOT NULL , `PASSWORD` VARCHAR(100) NOT NULL , `NAME` VARCHAR(100) NOT NULL , `ROLE` VARCHAR(20) NOT NULL , `DOB` DATE NOT NULL , `CONTACT_NO` VARCHAR(10) NOT NULL , `EMAIL` VARCHAR(50) NOT NULL , PRIMARY KEY (`USER_ID`)) ENGINE = InnoDB;